### PR TITLE
Add a number input explainer

### PR DESCRIPTION
**Pull request by lukewarlow**
Add a number input explainer along with a proposed anatomy

See https://github.com/openui/open-ui/pull/784 for the iniitial research PR. Once that's landed this changeset should get simpler.

### CODE REVIEW

**Comment by lukewarlow** [comment]
https://docs.google.com/document/d/13_Dxxszw2j8ELYUi2FAKPkeUZ1ddcKUnX_ZRGqPErXs/edit - Google doc to discuss this stuff further to come up with a good explainer @gregwhitworth (just copying from previous PR so it doesn't get lost)

**Comment by gregwhitworth** [comment]
I'm really liking this. That said, it seems like you're asking more questions rather than making a statement in your explainer. You landed the research. The proposal should link out to it, put your proposed anatomy in there and remove the "cruft". By all means have supporting arguments for why you're making the decisions you are (eg: making them siblings, etc).

**Comment by lukewarlow** [comment]
That makes sense, when I'm back I'll clean this up and get it ready to land an initial explainer, and then once we get stuff like the browser anatomies merged it'll provide even more evidence for this.

**Comment by lukewarlow** [comment]
Waiting on #784

**Pull request closed without merging**
