### PR TITLE
Change `alt` attributes to be empty

### PR DESCRIPTION
**Pull request by YummyBacon5**
For these images, the `alt` attribute should be empty because these images are decorational. Since all the info is already conveyed through the option's text.

Currently, a screen reader would announce "flag of USA USA" as the accessible name, which is verbose.

### CODE REVIEW

**Comment by gregwhitworth** [comment]
Agree with the complete redundancy here; but I'm curious if we should add an alt of "flag" to the image? This would result with an AT reading of "Image ... Flag ... USA, etc". I think I prefer your approach but would like @josepharhar to weigh in since he's primarily making the `selectlist` changes

**Comment by scottaohara** [comment]
These should have alt values. Flag isn’t useful here unless the intent is to choose a flag

**Review by scottaohara — APPROVED** [review]

**Comment by lukewarlow** [comment]
Not a blocker here but we should add label elements to each of the selectlists

**Review by coliff — APPROVED** [review]

**Comment by YummyBacon5** [comment]
Hey, please can this PR be merged now? Since it has been months

**Comment by lukewarlow** [comment]
@mfreed7 or @gregwhitworth would be good if one of you could approve so we can merge :)

**Comment by mfreed7** [comment]
> These shouldnt have alt values. Flag isn’t useful here unless the intent is to choose a flag

Based on this reply, this LGTM.

**Review by mfreed7 — APPROVED** [review]

**Comment by YummyBacon5** [comment]
It has been more months. This change does improve the accessible name. I guess I'm just not trusted enough to make these changes, lol.

Is there anything which I can change to get this merged?
@gregwhitworth, @dbaron, @josepharhar

**Comment by mfreed7** [comment]
> This branch has conflicts that must be resolved
Use the [web editor](https://github.com/openui/open-ui/pull/943/conflicts) or the  to resolve conflicts.
Conflicting files
site/src/pages/components/selectlist.mdx

Once you fix that, it [already has the needed approvals](https://github.com/openui/open-ui/pull/943#issuecomment-2076114140) to land.

**Comment by YummyBacon5** [comment]
Done

**Pull request merged**
