### PR TITLE
[Site rewrite] Migrate site to astro

### PR DESCRIPTION
**Pull request by andrico1234**

### CODE REVIEW

**Comment by andrico1234** [comment]
Small update

Managed to wire up the navigation 

image

**Comment by gregwhitworth** [comment]
@andrico1234 do you want to handle the merge conflicts?

**Comment by andrico1234** [comment]
WIll do!

**Comment by andrico1234** [comment]
image

Status update: Gradually making progress. Routing is works across the top-level pages. Bringing the styles together, then we can start doing a review of the site

**Comment by andrico1234** [comment]
Small update:

## Existing site
image


## Update site
image



Next steps are to get images resolving correctly, ensure navigation items are in the right order, test across devices

**Comment by andrico1234** [comment]
Very interesting (and positive) side effect of moving toward Astro:

The data transferred on load for one of the few interactive parts of the page has gone from 2.2mb to 175kb 😲 

before-data-transferred


after-data-transferred

**Comment by andrico1234** [comment]
Minor update:

Most things are complete, will need to do a deep check of the app,

but things are looking positive:

image


(note: the SEO issue brought up is due to a `noindex` directive, which I'm guessing that Netlify automatically applies to all preview servers so they don't get crawled by search engines)

**Review by gregwhitworth — CHANGES_REQUESTED** [review]
Thanks for this work @andrico1234 - it looks amazing. Apologies on the delayed review. A few minor requests/questions.

1. Can we please get rid of the /platform root folder and rename research to /site.
2. Can you please merge in main as there have been some changes since you updated last

Thanks and please mention me when you make those changes so we can try and land this asap.

Thank you again!!!

**Review by gregwhitworth — APPROVED** [review]

**Pull request merged**
