### PR TITLE
Adding Link research page

### PR DESCRIPTION
**Pull request by khmakoto**
This PR adds a research page under the `Analysis` section for the `Link` component and adds/updates the `concepts` for the libraries that have such a component.

### CODE REVIEW

**Review by gregwhitworth — APPROVED** [review]
This one raises an interesting point regarding how few actually have their own Link component and probably just use an anchor tag. I am approving the research but think this one should be raised to know whether this should be simply a definition proposal and not necessarily a full proposal due to its limited utilization across component libraries.

**Comment by khmakoto** [comment]
@gregwhitworth is there anything else I need to do here or should this be merged? Thanks!

**Comment by gregwhitworth** [comment]
@khmakoto can you file an issue regarding the below:

> I am approving the research but think this one should be raised to know whether this should be simply a definition proposal and not necessarily a full proposal due to its limited utilization across component libraries.

**Comment by gregwhitworth** [comment]
I'll merge after you link the issue to this PR

**Comment by khmakoto** [comment]
@gregwhitworth For sure! I've opened issue #257 regarding that.

**Comment by una** [comment]
Is it just me or are these images super tiny?

Screen Shot 2021-02-02 at 3 59 19 PM

**Comment by gregwhitworth** [comment]
@una based on the resolution in #257 should this PR be closed without merge?

**Comment by smhigley** [comment]
I don't know if this changes anything, but I at least found it interesting that two of the libraries provide a disabled link state, when that doesn't exist in HTML (or ARIA).

**Comment by chrisdholt** [comment]
> I don't know if this changes anything, but I at least found it interesting that two of the libraries provide a disabled link state, when that doesn't exist in HTML (or ARIA).

Yes, +1 to this. Link text should just appear as inline text as anchors without an href are treated as text. 

I'll add that there are visual implications with having this concept as well. While a disabled button does not need to meet contrast, a link which appears disabled is just text which *must* meet (currently) WCAG 2.1 AA contrast requirements.

**Comment by christopherallanperry** [comment]
@gregwhitworth, this looks like one that can now be closed without any additional effort being required from anyone.

**Comment by andrico1234** [comment]
Closing this based on: https://github.com/openui/open-ui/pull/253

**Pull request closed without merging**
