### PR TITLE
Rename `popup` to `popover` globally

### PR DESCRIPTION
**Pull request by mfreed7**
This follows the recent [OpenUI resolution](https://github.com/openui/open-ui/issues/627#issuecomment-1293918937) to rename the API.

### CODE REVIEW

**Comment by mfreed7** [comment]
Any thoughts on this one? I could use it landing - the API is now firmly the "Popover" API, but the explainer still thinks differently.

**Comment by mfreed7** [comment]
@gregwhitworth

**Comment by mfreed7** [comment]
@gregwhitworth any chance I could get a review of this PR, along with [this one](https://github.com/openui/open-ui/pull/630) and [this one](https://github.com/openui/open-ui/pull/628)?

These have been hanging out for 2 weeks, and we've already updated all of the blog posts and implementation to match. People will get confused if they go read the explainer right now.

Also, and very related, is [this issue](https://github.com/openui/open-ui/issues/634). I'd really like the URL to also say "popover" but I need to redirect from the old "popup" URL. I don't know how to do that.

**Review by jonathantneal — APPROVED** [review]

**Review by andrico1234 — APPROVED** [review]

**Comment by mfreed7** [comment]
Thanks!

**Pull request merged**
