### PR TITLE
Add form semantics section

### PR DESCRIPTION
**Pull request by josepharhar**
fixes https://github.com/openui/open-ui/issues/705

### CODE REVIEW

**Review by andrico1234 — APPROVED** [review]

**Comment by andrico1234** [comment]
Thanks for this 😄

Happy for you to merge any time incase you want anyone to review the content

**Comment by gregwhitworth** [comment]
@dandclark will you have a chance to review this, if not - I can possibly give it a review sometime this week.

**Comment by josepharhar** [comment]
Can we merge this?

**Comment by josepharhar** [comment]
There has been plenty of time for review, I'm going to merge this now

**Pull request merged**
