### PR TITLE
Rename selectmenu to selectlist

### PR DESCRIPTION
**Pull request by josepharhar**
This was resolved here:
https://github.com/openui/open-ui/issues/773

### CODE REVIEW

**Comment by josepharhar** [comment]
@andrico1234 do you know why this build failed?

**Comment by gregwhitworth** [comment]
@josepharhar logs show the following problems:

```
1:28:03 PM: [1/4] Resolving packages...
1:28:03 PM: warning @fortawesome/fontawesome-svg-core@1.3.0: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
1:28:03 PM: warning @fortawesome/fontawesome-svg-core > @fortawesome/fontawesome-common-types@0.3.0: Please upgrade to 6.1.0. https://fontawesome.com/docs/changelog/
1:28:13 PM: error Couldn't find any versions for astro-compress that matches ^1.1.10
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
1:28:13 PM: Error during Yarn install
1:28:13 PM: Build was terminated: dependency_installation script returned non-zero exit code: 1
1:28:13 PM: Failing build: Failed to install dependencies
```

**Review by mfreed7 — APPROVED** [review]
I'm assuming this is a pure search/replace of "selectmenu" with "selectlist". (It's hard to tell because the diff doesn't think it's a rename.)

Assuming so, LGTM.

**Comment by andrico1234** [comment]
Sorry for the delay folks, I have a PR open for this fix (along with a description of the problem). 

https://github.com/openui/open-ui/pull/791

@josepharhar , you'll likely need to merge from main once my fix goes in. Let me know if you need a hand with anything else :)

**Comment by andrico1234** [comment]
CC - @josepharhar 

The fix has been merged, you should be unblocked now 😄

**Comment by josepharhar** [comment]
Thanks, I merged with the new commits.
Weird though, it looks like there were no checks that ran on my latest commit. I'll click the "squash and merge" button anyway since it seems happy

**Pull request merged**
